# Generated by Django 3.2.6 on 2021-08-08 14:29

from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('coordinates', location_field.models.spatial.LocationField(srid=4326)),
                ('logo', models.ImageField(upload_to='logos')),
            ],
        ),
    ]
